# Customized for Donatello

obstacle_range: 2.5
raytrace_range: 3
max_obstacle_height: 2.0
footprint_padding: 0.01

#robot_radius : 0.25
footprint: [[-0.38, -0.38], [-0.38, 0.38], [0.38, 0.38], [0.38, -0.38]]

#layer definitions
static:
    map_topic: /map

obstacles:
    observation_sources: scan
    scan: {data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true, min_obstacle_height: -0.2, max_obstacle_height: 1.0} #2

inflation:
    cost_scaling_factor:  10
    inflation_radius: 0.55
    inflate_unknown : False
    ethal_cost_threshold: 100
